controller_server:
  ros__parameters:
    use_sim_time: false
    controller_plugins: ["FollowPath"]

    FollowPath:
      plugin: "nav2_mpc_controller/MpcController"

      # MPC
      N: 15
      dt: 0.1

      # Limits
      v_max: 0.5
      v_min: -0.1
      w_max: 1.5

      dv_max: 0.5
      dw_max: 2.5

      # Costs
      w_pos: 6.0
      w_yaw: 2.0
      w_v: 0.2
      w_w: 0.2
      w_dv: 0.6
      w_dw: 0.6

      # Optimizer
      opt_iters: 20
      step_size: 0.3
      grad_eps: 1e-3

      # Path handling
      prune_dist: 2.5
      ref_stride: 1
      transform_tolerance: 0.2

      # Output smoothing
      cmd_smoothing: 0.2
